version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper 
    ports:
      - "2181:2181"
    networks:
      - opener-network
  kafka:
    container_name: kafka
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: k8c104.p.ssafy.io:9092    
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - opener-network
networks:
  opener-network:
    external: true