import Link from 'next/link';
import './globals.css';
import TopNav from './components/TopNav';
import BottomNav from './components/BottomNav';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>OPENER</title>
      </head>
      <body className="border-2 m-3 p-3 h-[700px] relative min-w-[500px]">
        <TopNav />
        <div className="pb-[68px] shadow-xl">{children}</div>
        <BottomNav />
      </body>
    </html>
  );
}
